spring:
  application:
    name: Build-a-bear
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/buildabear
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: false
client: http://localhost:5173
token:
  signing:
    key: 413F3138472B4B6250655368566D5970337336763879244226452948404D6351
security:
  username: admin
  password: secure
